spring:
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1"
    driver-class-name: org.h2.Driver
    username: user
    password: password
    platform: h2
    initialization-mode: always
  flyway:
    schemas: PUBLIC
    url: "jdbc:h2:mem:default;DB_CLOSE_DELAY=-1"
    user: user
    password: password
  h2:
    console:
      enabled: true